gitChecks: false

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.1.0
  vite-plus: 1.1.0

overrides:
  vite@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"

allowBuilds:
  "@google/genai": false
  esbuild: true
  protobufjs: false

minimumReleaseAgeExclude:
  - "@agntn/*"
